// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  experiences: dynamic(() => import("./Experiences")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  rich_text: dynamic(() => import("./RichText")),
  skills: dynamic(() => import("./Skills")),
};
