// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type FooterDocumentDataSlicesSlice = FooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = HeaderSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ContactSlice
  | FooterSlice
  | ExperiencesSlice
  | HeaderSlice
  | ProjectsSlice
  | SkillsSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | FooterSlice
  | HeaderSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | PageDocument;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Badge field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Me
   * - **API ID Path**: contact.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Section Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  designation: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Image field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Experiences → Default → Primary → Experiences*
 */
export interface ExperiencesSliceDefaultPrimaryExperiencesItem {
  /**
   * Designation field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  designation: prismic.KeyTextField;

  /**
   * Description field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Start Time field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].start_time
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_time: prismic.DateField;

  /**
   * End Time field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].end_time
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_time: prismic.DateField;

  /**
   * Currently Working field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: experiences.default.primary.experiences[].currently_working
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  currently_working: prismic.BooleanField;

  /**
   * Image field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Experiences → Default → Primary → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Experiences → Default → Primary*
 */
export interface ExperiencesSliceDefaultPrimary {
  /**
   * Badge field in *Experiences → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Section Description field in *Experiences → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Experiences field in *Experiences → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.default.primary.experiences[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  experiences: prismic.GroupField<
    Simplify<ExperiencesSliceDefaultPrimaryExperiencesItem>
  >;
}

/**
 * Default variation for Experiences Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperiencesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperiencesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Experiences*
 */
type ExperiencesSliceVariation = ExperiencesSliceDefault;

/**
 * Experiences Shared Slice
 *
 * - **API ID**: `experiences`
 * - **Description**: Experiences
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperiencesSlice = prismic.SharedSlice<
  "experiences",
  ExperiencesSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Name field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  designation: prismic.KeyTextField;

  /**
   * Location field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Email field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * External Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.external_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Social Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_links: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Footer Credit Text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: CopyRight [current_year]
   * - **API ID Path**: footer.default.primary.footer_credit_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_credit_text: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Logo Text field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  logo_text: prismic.KeyTextField;

  /**
   * Logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Header Links field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.header_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Github Link field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.github_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Logo Link field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  logo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Social Links*
 */
export interface HeroSliceDefaultPrimarySocialLinksItem {
  /**
   * Link Name field in *Hero → Default → Primary → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Social
   * - **API ID Path**: hero.default.primary.social_links[].link_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_name: prismic.KeyTextField;

  /**
   * Link field in *Hero → Default → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com/
   * - **API ID Path**: hero.default.primary.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hello Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hello, I am
   * - **API ID Path**: hero.default.primary.hello_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hello_text: prismic.KeyTextField;

  /**
   * Developer Full Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Mr. Charm
   * - **API ID Path**: hero.default.primary.developer_full_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  developer_full_name: prismic.KeyTextField;

  /**
   * Developer Bio field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learning and building web applications with a focus on user experience and performance.
   * - **API ID Path**: hero.default.primary.developer_bio
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  developer_bio: prismic.KeyTextField;

  /**
   * Social Links field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimarySocialLinksItem>
  >;

  /**
   * Developer Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.developer_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  developer_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Projects → Default → Primary → Projects*
 */
export interface ProjectsSliceDefaultPrimaryProjectsItem {
  /**
   * Description field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Title field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Live Link field in *Projects → Default → Primary → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[].live_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Badge field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Projects
   * - **API ID Path**: projects.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Section Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Some of the noteworthy projects I have built:
   * - **API ID Path**: projects.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Projects field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  projects: prismic.GroupField<
    Simplify<ProjectsSliceDefaultPrimaryProjectsItem>
  >;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Skills → Default → Primary → Skills*
 */
export interface SkillsSliceDefaultPrimarySkillsItem {
  /**
   * Skill Name field in *Skills → Default → Primary → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[].skill_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_name: prismic.KeyTextField;

  /**
   * Skill Logo field in *Skills → Default → Primary → Skills*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[].skill_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  skill_logo: prismic.ImageField<never>;

  /**
   * Description field in *Skills → Default → Primary → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Badge field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Skills
   * - **API ID Path**: skills.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Section Description field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The skills, tools and technologies I am really good at:
   * - **API ID Path**: skills.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Skills field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  skills: prismic.GroupField<Simplify<SkillsSliceDefaultPrimarySkillsItem>>;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      ExperiencesSlice,
      ExperiencesSliceDefaultPrimaryExperiencesItem,
      ExperiencesSliceDefaultPrimary,
      ExperiencesSliceVariation,
      ExperiencesSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimarySocialLinksItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryProjectsItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimarySkillsItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
